dicussion_board/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path

from  django.urls import path ,include
from boards import views
urlpatterns = [
    path("admin/", admin.site.urls),
   path('',include('boards.url'))
]

boards/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Board(models.Model):
   name=models.CharField(max_length=50,unique=True) 
   description=models.CharField(max_length=150) 

   def __str__(self):
     return self.name


class Topic(models.Model):
     subject=models.CharField(max_length=255)   
     Board=models.ForeignKey(Board, related_name='topic',on_delete=models.CASCADE) 
     created_by=models.ForeignKey(User,related_name='topics', on_delete=models.CASCADE)
     created_dt=models.DateField(auto_now_add=True) 

boards/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Board


# Create your views here.
def home(request):
    boards = Board.objects.all()
    return render(request, 'home.html', {'boards': boards})


 # Make sure Board is imported correctly


def boards_topics(request, board_id):
    # try:
    #     board = Board.objects.get(pk=board_id)
    # except Board.DoesNotExist:
    #     raise Http404  # This will return a 404 page if the board doesn't exist
    board=get_object_or_404(Board,pk=board_id)
    return render(request, 'topics.html', {'board': board})
def new_topic(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    return render(request, 'new_topic.html', {'board': board})

templates/base.html
  {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    <div class="container">
        <li class="text-secondary">
            <a href="{% url 'index' %}">Boards</a>
        </li>
        {% block content %}
        {% endblock content %}
         {% block foued %}
        {% endblock foued %}
    </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
    Boards
{% endblock title %}

{% block content %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Board</th>
                <th>Post</th>
                <th>Topic</th>
                <th>Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
            <tr>
                <td>
                    <a href="{% url 'board_topic' board.pk %}">{{ board.name }}</a>
                    <small class="text-muted d-block">{{ board.description }}</small>
                </td>
                <td>0</td>
                <td>0</td>
                <td></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/new_topic.html
{% extends 'base.html' %}


{% block title %}
    create new topic
{% endblock title %}

{% block content %}
    <h1>Hello Hichem</h1>
    <div class="container">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active"> <a href="{% url 'board_topic' board.pk%}">{{ board.name }}</a></li>
            <li class="breadcrumb-item active">new topic</li>
        </ul>
    </div>
{% endblock content %}


{% block  foued %}

<form method="post">
    <label> subject</label>
    <input type="text" name="subject" id="id_subject">
</form>
{% endblock  %}

templates/topics.html
{% extends 'base.html' %}


{% block title %}
    {{ board.name }}
{% endblock title %}

{% block content %}
    <h1>Hello Hichem</h1>
    <div class="container">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active">{{ board.name }}</li>
        </ul>
    </div>